export const authTypes = {
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_FULFILLED: 'REGISTER_USER_FULFILLED',
  REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_FULFILLED: 'LOGIN_USER_FULFILLED',
  LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
  LOGIN_USER_BY_TOKEN: 'LOGIN_USER_BY_TOKEN',
  LOGIN_USER_BY_TOKEN_FAILED: 'LOGIN_USER_BY_TOKEN_FAILED',
  LOG_OUT_USER: 'LOG_OUT_USER',
}
