export const groupsTypes = {
  ADD_GROUP: 'ADD_GROUP',
  ADD_GROUP_FULFILLED: 'ADD_GROUP_FULFILLED',
  ADD_GROUP_FAILED: 'ADD_GROUP_FAILED',
  GET_GROUPS: 'GET_GROUPS',
  GET_GROUPS_FULFILLED: 'GET_GROUPS_FULFILLED',
  GET_GROUPS_FAILED: 'GET_GROUPS_FAILED',
  CLEAR_GROUPS: 'CLEAR_GROUPS',
}
