export default {
  INIT: 'INIT',
  ADD_TASK: 'ADD_TASK',
  ADD_GROUP: 'ADD_GROUP',
  SET_TASKS: 'SET_TASKS',
  SET_GROUPS: 'SET_GROUPS',
  SET_DATA_READY: 'SET_DATA_READY',
  SET_INIT_DATA: 'SET_INIT_DATA',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASK_FULFILLED: 'REMOVE_TASK_FULFILLED',
}
