export const tasksTypes = {
  ADD_TASK: 'ADD_TASK',
  ADD_TASK_FULFILLED: 'ADD_TASK_FULFILLED',
  ADD_TASK_FAILED: 'ADD_TASK_FAILED',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASK_FULFILLED: 'REMOVE_TASK_FULFILLED',
  REMOVE_TASK_FAILED: 'REMOVE_TASK_FAILED',
  UPDATE_TASK: 'UPDATE_TASK',
  UPDATE_TASK_FULFILLED: 'UPDATE_TASK_FULFILLED',
  UPDATE_TASK_FAILED: 'UPDATE_TASK_FAILED',
}
