export default {
  ADD_TASK: 'ADD_TASK',
  ADD_TASK_FULFILLED: 'ADD_TASK_FULFILLED',
  ADD_TASK_FAILED: 'ADD_TASK_FAILED',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASK_FULFILLED: 'REMOVE_TASK_FULFILLED',
  REMOVE_TASK_FAILED: 'REMOVE_TASK_FAILED',
  SET_TASKS: 'SET_TASKS',
}
